config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve', on: :member
  end
  resources :product_categories, only: %i[index show new create destroy]

  resources :coupons, only: %i[index] do
    post 'inactivate', on: :member
    post 'reactivate', on: :member
  end

  namespace 'api' do
    namespace 'v1' do
      get 'coupons/:code', to: 'coupons#show'
      post 'coupons/:code/burn', to: 'coupons#burn'
    end
  end
end

app/models/coupon.rb
# frozen_string_literal: true

class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, inactive: 20, burn: 10 }
  delegate :expiration_date, :discount_rate, to: :promotion

  def self.search(search)
    where(code: search) if search
  end

  def title
    "#{code} (#{Coupon.human_attribute_name("status.#{status}")})"
  end

  def as_json(options = {})
    super({ methods: %i[discount_rate expiration_date],
            only: %i[] }.merge(options))
  end

  def burn!(order)
    raise ActiveRecord::RecordInvalid if order.blank?

    update!(order: order, status: :burn)
  end

  def valid_category?(category)
    return true if promotion.product_categories.count.zero? || promotion.product_categories.find_by(code: category)

    false
  end
end

app/controllers/api/v1/coupons_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CouponsController < ApiController
      before_action :set_coupon, only: %i[show burn]

      def show
        if @coupon.promotion.expired?
          render json: 'Cupom expirado', status: :precondition_failed
        else
          render json: @coupon.promotion, status: :ok
        end
      end

      def burn
        @coupon.order = params.require(:order).permit(:code)[:code]
        unless @coupon.valid_category? params[:category]
          return render json: 'Categoria inválida para cupom',
                        status: :bad_request
        end

        @coupon.burn!(params.require(:order).permit(:code)[:code])

        @coupon.update(order: params[:order][:code], status: :burn)

        render json: 'Cupom utilizado com sucesso', status: :ok
      rescue ActionController::ParameterMissing
        render json: '', status: :precondition_failed
      rescue ActiveRecord::RecordInvalid
        render json: '', status: :unprocessable_entity
      end

      private

      def set_coupon
        @coupon = Coupon.find_by!(code: params[:code])
      rescue ActiveRecord::RecordNotFound
        render json: 'Cupom não encontrado', status: :not_found
      end
    end
  end
end

app/controllers/coupons_controller.rb
# frozen_string_literal: true

class CouponsController < ApplicationController
  before_action :authenticate_user!

  def index
    @coupons = Coupon.search(params[:coupons_query])
  end

  def inactivate
    @coupon = Coupon.find(params[:id])
    @coupon.inactive!
    flash[:success] = 'Cupom cancelado com sucesso'
    redirect_to @coupon.promotion
  end

  def reactivate
    @coupon = Coupon.find(params[:id])
    @coupon.active!
    flash[:success] = 'Cupom reativado com sucesso'
    redirect_to @coupon.promotion
  end
end

app/helpers/coupons_helper.rb
# frozen_string_literal: true

module CouponsHelper
end

app/views/coupons/_coupon.html.erb
<ul class="list-group list-group-flush">
  <li class="list-group-item">Código: <%= coupon.code %> <%= coupon.title %></li>
  <% if coupon.active? %>
    <li class="list-group-item"> <%= link_to 'Desativar cupom', inactivate_coupon_path(coupon), method: :post %></li>
    <% else %>
    <li class="list-group-item"><%= link_to 'Reativar cupom', reactivate_coupon_path(coupon), method: :post, class: "ls-btn-primary" %></li>
  <% end %>
</ul>

app/views/coupons/_coupon_search.html.erb
<%= form_tag coupons_path, :method => 'get' do %>
  <%= text_field_tag :coupons_query, params[:coupons_query], class: "ls-field" %>
  <%= submit_tag 'Buscar cupom', :name => nil, class: "ls-btn" %>
<% end %>

app/views/coupons/index.html.erb
<% @coupons.each do |coupon| %>
  <div class="card">
    <div class="card-body">
      <%= render partial: 'coupon', locals: { coupon: coupon } %>
      <%= render partial: 'promotions/card', locals: { promotion: coupon.promotion, title_promotion: 'Promoção: ' } %>
    </div>
  </div>
<% end %>

<% if @coupons.empty? %>
  <p>Nenhum cupom encontrado</p>
<% end %>