config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve', on: :member
  end
  resources :product_categories, only: %i[index show new create destroy]

  resources :coupons, only: %i[index] do
    post 'inactivate', on: :member
    post 'reactivate', on: :member
  end

  namespace 'api' do
    namespace 'v1' do
      get 'coupons/:code', to: 'coupons#show'
      post 'coupons/:code/burn', to: 'coupons#burn'
    end
  end
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/marisnner7"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/marianne-aguiar-dev/"><i class="fab fa-linkedin"></i></a>
    <a href="https://www.marianneag.dev/"><i class="fas fa-blog"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "coupons.png" %>
      <% end %>
      
      <%= render 'promotions/search' %>
      <%= render 'coupons/coupon_search' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Promoções", promotions_path , class: "nav-link btn btn-outline-info " %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
          </li>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>

          <% end %>
          <li class="nav-item dropdown">
            <%= image_tag "locaweb.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>   