config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve', on: :member
  end
  resources :product_categories, only: %i[index show new create destroy]

  resources :coupons, only: %i[index] do
    post 'inactivate', on: :member
    post 'reactivate', on: :member
  end

  namespace 'api' do
    namespace 'v1' do
      get 'coupons/:code', to: 'coupons#show'
      post 'coupons/:code/burn', to: 'coupons#burn'
    end
  end
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  has_many :product_category_promotions, dependent: :delete_all
  has_many :promotions, through: :product_category_promotions

  validates :name, :code, presence: { message: 'não pode ficar em branco' }
  validates :name, :code, uniqueness: { message: 'já está em uso' }
end

app/controllers/product_categories_controller.rb
# frozen_string_literal: true

class ProductCategoriesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_product_category, only: %i[show destroy]
  def index
    @product_categories = ProductCategory.all
  end

  def show; end

  def new
    @product_category = ProductCategory.new
  end

  def create
    @product_category = ProductCategory.new(product_category_params)
    if @product_category.save
      redirect_to product_categories_path(@product_category)
    else
      render :new
    end
  end

  def destroy
    @product_category.destroy
    redirect_to product_categories_path, notice: 'Categoria deletada com sucesso'
  end

  private

  def set_product_category
    @product_category = ProductCategory.find(params[:id])
  end

  def product_category_params
    params.require(:product_category).permit(:name, :code)
  end
end

app/helpers/product_categories_helper.rb
# frozen_string_literal: true

module ProductCategoriesHelper
end

app/views/product_categories/_form_category.html.erb
<div class="container">
  <%= simple_form_for @product_category do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :code %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>
</div>

app/views/product_categories/index.html.erb
<%= link_to "Registrar categoria de produto", new_product_category_path , class: 'btn btn-outline-secondary' %>
  
<% @product_categories.each do |product_category| %>
  <div class="container">
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">  <%= link_to product_category.name, product_category_path(product_category)  %></li>
          <li class="list-group-item">  <%= product_category.code %> </li>
        </ul>
      </div>
    </div>
<% end %>
  <%= "Nenhuma categoria cadastrada" if @product_categories.empty? %>

app/views/product_categories/new.html.erb
<%= render 'form_category', product_category: @product_category %>

app/views/product_categories/show.html.erb
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @product_category.name %></li>
    <li class="list-group-item"><%= @product_category.code %></li>
    <%= link_to 'Deletar Categoria', product_category_path, method: :delete , class: "btn btn-outline-danger" %>
  </ul>
  <%= link_to "Voltar", product_categories_path, class:'btn btn-outline-secondary' %>
</div>