config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve', on: :member
  end
  resources :product_categories, only: %i[index show new create destroy]

  resources :coupons, only: %i[index] do
    post 'inactivate', on: :member
    post 'reactivate', on: :member
  end

  namespace 'api' do
    namespace 'v1' do
      get 'coupons/:code', to: 'coupons#show'
      post 'coupons/:code/burn', to: 'coupons#burn'
    end
  end
end

app/models/promotion.rb
# frozen_string_literal: true

class Promotion < ApplicationRecord
  has_many :coupons, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'creator_id', optional: true
  belongs_to :user, class_name: 'User', foreign_key: 'approver_id', optional: true
  has_many :product_category_promotions, dependent: :destroy
  has_many :product_categories, through: :product_category_promotions

  validates :name, :code, :discount_rate,
            :coupon_quantity, :expiration_date, presence: { message: 'não pode ficar em branco' }
  validates :code, uniqueness: { message: 'deve ser único' }

  def generate_coupons!
    raise 'Cupons já foram gerados' if coupons.any?

    coupons
      .create_with(created_at: Time.zone.now, updated_at: Time.zone.now)
      .insert_all!(generate_coupons_code)
  end

  def expired?
    expiration_date < Date.current
  end

  def approved?
    approved_at?
  end

  private

  def generate_coupons_code
    (1..coupon_quantity).map do |number|
      { code: "#{code}-#{'%04d' % number}" }
    end
  end
end

app/controllers/promotions_controller.rb
# frozen_string_literal: true

class PromotionsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_promotion, only: %i[show edit update destroy generate_coupons]
  def index
    @promotions = Promotion.all
    @search = params['search']
    return if @search.blank?

    @name = @search['name']
    @promotions = Promotion.where('name ILIKE ?', "%#{@name}%")
  end

  def show; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.create(promotion_params)
    @promotion.creator_id = User.find(current_user.id).id

    if @promotion.save
      redirect_to promotion_path(@promotion)
    else
      render :new
    end
  end

  def edit; end

  def update
    @promotion.update(promotion_params)
    redirect_to promotion_path, notice: 'Promoção editada'
  end

  def destroy
    @promotion.destroy
    redirect_to promotions_path, notice: 'Promoção deletada com sucesso'
  end

  def generate_coupons
    @promotion.generate_coupons!
    flash[:success] = 'Cupons gerados com sucesso'
    redirect_to @promotion
  end

  def approve
    @promotion = Promotion.find(params[:id])
    @promotion.update(approver_id: current_user.id, approved_at: Time.zone.now)

    redirect_to promotion_path(@promotion)
  end

  private

  def promotion_params
    params.require(:promotion).permit(:name, :description, :code, :discount_rate, :coupon_quantity,
                                      :expiration_date, product_category_ids: [])
  end

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end
end

app/helpers/promotions_helper.rb
# frozen_string_literal: true

module PromotionsHelper
end

app/views/promotions/_card.html.erb
<div class="container" >
  <div class="card border-success mb-3" style="max-width: 18rem;">
    <div class="card-header"><strong class="card-text"> <%= link_to promotion.name, promotion %></strong></div>
      <p class="card-text"><%= promotion.description %></p>
      <p>Código: <%= link_to promotion.code, promotion_path(promotion) %> </p>
      <p>Desconto: <%= number_to_percentage promotion.discount_rate, precision: 2, separator: ',' %></p>
      <p>Quantidade de Cupons: <%= promotion.coupon_quantity %></p>
      <p>Expiração: <%= promotion.expiration_date.strftime('%d/%m/%Y') %></p>
  </div>
</div>

app/views/promotions/_form.html.erb
<div class="container">
  <%= simple_form_for @promotion do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :code %>
    <%= f.input :discount_rate %>
    <%= f.input :expiration_date, :order => [:day, :month, :year] %>
    <%= f.input :coupon_quantity %>
    <%= f.association :product_categories, as: :check_boxes %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>
</div>

app/views/promotions/_search.html.erb
<%= simple_form_for :search, url: promotions_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :name, input_html: {value: ""} %>   
  <%= f.submit "Buscar promoção", class: "btn btn-primary" %>

<% end %>

app/views/promotions/edit.html.erb
<%= render 'form', promotion: @promotion %>

app/views/promotions/index.html.erb
<%= "Nenhuma promoção encontrada" if @promotions.empty? %>

<%= link_to 'Registrar uma promoção', new_promotion_path, class: 'btn btn-success' %>
<%= link_to 'Voltar' , root_path , class: 'btn btn-secondary'%>

<% @promotions.each do |promotion| %>
    <%= render partial: "card", locals: { promotion: promotion, title_promotion: ''} %>
  <% end %>

app/views/promotions/new.html.erb
<%= render 'form', promotion: @promotion %>

app/views/promotions/show.html.erb
<div class="card">
  <div class="card-header">
    Nome: <%= @promotion.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Descrição: <%= @promotion.description %></h5>
    <p class="card-text">Código: <%= @promotion.code %></p>
    <p class="card-text">Desconto: <%= number_to_percentage @promotion.discount_rate, precision: 2, separator: ',' %></p>
    <p class="card-text">Quantidade: <%= @promotion.coupon_quantity %></p>
    <p class="card-text">Expiração: <%= @promotion.expiration_date.strftime('%d/%m/%Y') %></p>
      <% @promotion.product_categories.each do |product_category| %>
        <p  class="card-text">Categoria: <%= product_category.name %></p>
      <% end %>
  </div>

     <% if @promotion.approved? %>
        <p class="card-header">Promoção aprovada em <%= @promotion.approved_at %></p>
      <% end %>

    <% if current_user.id == @promotion.creator_id && !@promotion.approved? %>
      <p class="btn btn-outline-warning">Aguardando aprovação</p>
      <% elsif current_user.id != @promotion.creator_id && !@promotion.approved? %>
        <%= link_to 'Aprovar promoção', approve_promotion_path(@promotion), method: :post, class: "btn btn-success" %>
      <% elsif @promotion.approved? && @promotion.coupons.empty? %>
        <%= link_to 'Gerar cupons', generate_coupons_promotion_path, method: :post , class:'btn btn-primary'%>
    <% end %>

    <%= link_to 'Editar', edit_promotion_path, class:'btn btn-info'%>
    <%= link_to 'Deletar promoção', promotion_path, method: :delete, class: 'btn btn-danger' %>
    <%= link_to 'Voltar', promotions_path, class:'btn btn-secondary' %>
</div>


<div class="card" style="width: 18rem;">
  <h3>Cupons</h3>
   <%= render @promotion.coupons %>
</div>